on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: make release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: create release
        run: |
          make --always-make release
